name: Deploy Quartz site to GitHub Pages

on:
  push:
    branches:
      - v4

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for git info
      - uses: actions/setup-node@v3
        with:
          node-version: 18.14

      - name: Install Pandoc and CSL dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc pandoc-citeproc
          curl -o your-style.csl https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl # Replace with your CSL file URL

      - name: Convert Markdown to Markdown with Citations
        run: |
          mkdir converted_md
          for file in contents/*.md; do
            pandoc "$file" --filter pandoc-citeproc --bibliography="references/zotero_library.bib" --csl=your-style.csl -t markdown -o "converted_md/$(basename "$file")"
          done

      - name: Move converted files to contents
        run: |
          rm -rf contents
          mv converted_md contents

      - name: Install Dependencies
        run: npm ci

      - name: Build Quartz
        run: npx quartz build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: public

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
